config/routes.rb
Rails.application.routes.draw do
  # root to 'restaurants#index'
  # get '/restaurants', to: 'restaurants#index', as: :restaurants
  # get '/restaurants/new', to: 'restaurants#new', as: :new_restaurant
  # get '/restaurants/:id', to: 'restaurants#show', as: :restaurant
  # post '/restaurants', to: 'restaurants#create'
  # get '/restaurants/:id/edit', to: 'restaurants#edit', as: :edit_restaurant
  # patch '/restaurants/:id', to: 'restaurants#update'
  # delete '/restaurants/:id', to: 'restaurants#destroy'
  resources :restaurants do
    resources :reviews, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"], message: "only accept chinese, italian, japanese, french, belgian" }

  def average_rating
    return '-' if self.reviews.empty?

    ratings = self.reviews.map { |review| review.rating }
    return (ratings.sum / ratings.length.to_f).round(1)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :restaurant, :content, :rating, presence: true
  validates :rating, inclusion: { in: (0..5).to_a, message: "must be numbers between 0 and 5" }, numericality: { only_integer: true }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [:show, :edit, :update, :destroy]

  def create
    @restaurant = Restaurant.new(resto_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def index
    @restaurants = Restaurant.all
  end

  def show
    @review = Review.new
  end

  def edit
  end

  def update
    if @restaurant.update(resto_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy

    redirect_to restaurants_path
  end

  private

  def resto_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between border-bottom mb-4">
      <%= link_to 'Rails Yelp MVP', restaurants_path, class: 'navbar-brand' %>
        <form class="form-inline my-2 my-lg-0">
          <%= link_to 'New Restaurant', new_restaurant_path, class: 'btn btn-outline-success' %>
        </form>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit class: 'btn btn-outline-primary' %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Restaurants#edit</h1>
<p>Find me in app/views/restaurants/edit.html.erb</p>

<%= render 'form' %>

app/views/restaurants/index.html.erb
<h1>Welcome to Yelppie</h1>
<p>Your Restaurant Finder of Choice :)</p>

<% @restaurants.each do |restaurant| %>
    <div class="card my-2 p-2">
      <div>
        <h4><%= link_to restaurant.name, restaurant_path(restaurant) %></h4>
        <p>Average Rating: <%= restaurant.average_rating %></p>
      </div>
      <div>
        <span>
          <%= link_to edit_restaurant_path(restaurant) do %>
            <i class="fas fa-edit"></i>
          <% end %>
          <%= link_to restaurant_path(restaurant), method: :delete, data: { confirm: "Are you sure?" } do %>
            <i class="far fa-trash-alt"></i>
          <% end %>
        </span>
      </div>
    </div>
<% end %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %>
  <span>
    <%= link_to edit_restaurant_path(@restaurant) do %>
      <i class="fas fa-edit"></i>
    <% end %>
    <%= link_to restaurant_path(@restaurant), method: :delete, data: { confirm: "Are you sure?" } do %>
      <i class="far fa-trash-alt"></i>
    <% end %>
  </span>
</h1>

<p><%= @restaurant.address %></h4>
<p><%= @restaurant.phone_number %></p>
<p><%= @restaurant.category %></p>
<p>Average Rating: <%= @restaurant.average_rating %></p>

<% @restaurant.reviews.each do |review| %>
  <div class="card my-2 p-2">
    <h4><%= review.content %></h4>
    <p>Rating: <%= review.rating %></p>
  </div>
<% end %>

<div class="card my-2 p-4">
  <h2>Write a review</h2>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit class: 'btn btn-outline-primary' %>
  <% end %>
</div>